name: Build server image
description: Builds server image and pushes to Docker Hub

inputs:
  ARCH:
    description: "Docker build architecture (amd64 or arm64)."
    required: false
    default: amd64

outputs:
  tag:
    description: "The tag of the built image"
    value: ${{ steps.build-image.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Build and push server image
      shell: bash
      id: build-image
      run: bun run .github/scripts/src/build-server --getGhaOutput=true --arch="${{ inputs.ARCH }}"
